kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/pwd/keybase
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
