pipeline:
  docker:
    image: plugins/docker
    registry: registry.makerforce.io
    secrets: [ docker_username, docker_password ]
    repo: registry.makerforce.io/pwd/keybase
    tags:
      - latest
